// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBX5E8HZMNQgZ0YGvim8hflcWvGlJp3CuU',
    appId: '1:1056068711079:web:74522b132c557357e82182',
    messagingSenderId: '1056068711079',
    projectId: 'kajetan-polcyn',
    authDomain: 'kajetan-polcyn.firebaseapp.com',
    storageBucket: 'kajetan-polcyn.appspot.com',
    measurementId: 'G-1ENFWQG7VQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcZLAPVNQ9sh6pSYsvVhyxFMR1cdpaeMM',
    appId: '1:1056068711079:android:3781daaf2666dfe2e82182',
    messagingSenderId: '1056068711079',
    projectId: 'kajetan-polcyn',
    storageBucket: 'kajetan-polcyn.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtcU0awZ2vLP_CX0pRxLEf5QDcYpWg1FQ',
    appId: '1:1056068711079:ios:faa6eaa5c4d53959e82182',
    messagingSenderId: '1056068711079',
    projectId: 'kajetan-polcyn',
    storageBucket: 'kajetan-polcyn.appspot.com',
    iosBundleId: 'com.example.portfolioApp',
  );
}
